server:
  port: 9000
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-server
  codec:
    max-in-memory-size: 20MB
  cloud:
    gateway:
      httpclient:
        response-timeout: 5s
        connect-timeout: 5000
        pool:
          max-idle-time: 10000
          acquire-timeout: 10000
        max-initial-line-length: 10485760 # 10MB
        max-header-size: 20MB
        max-chunk-size: 20MB
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: RequestSize
          args:
            maxSize: 20MB
      routes:
        - id: auth
          uri: http://localhost:4000
          predicates:
            - Path=/userinfo  # 添加 Bearer Token
          filters:
            - StripPrefix=1
        - id: basic-system
          uri: lb://basicsystem
          predicates:
            - Path=/basic-system/**
          filters:
            - StripPrefix=1
        - id: article
          uri: lb://article
          predicates:
            - Path=/public/v1/article/**
          filters:
            - StripPrefix=1
        - id: file
          uri: lb://file-center
          predicates:
            - Path=/protected/v1/file/**, /public/v1/file/**
          filters:
            - StripPrefix=1
        - id: IMS
          uri: lb://InventoryMgtSystem
          predicates:
            - Path=/ims/**
          filters:
            - StripPrefix=1
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:4000


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: debug