spring:
  application:
    name: auth-server
server:
  port: 4000

logging:
  level:
    org.springframework.security: TRACE
    root: trace

dubbo:
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848
    register-mode: instance

management:
  endpoints:
    web:
      exposure:
        include: "*"